### ISSUE TITLE
Dkim sign when body is empty

### ISSUE THREAD

**Issue by twawszczak** [andris9/dkim-signer#2]
https://github.com/andris9/dkim-signer/blob/b24db1af973891145b7c68635b66b9f1a9ffe9ce/lib/dkim.js#L34

Is that part correct? Here you get whole mail (with headers), when body not found. But in docs:

http://dkim.org/specs/rfc4871-dkimbase.html#simple-body
"Note that a completely empty or missing body is canonicalized as a single "CRLF"; that is, the canonicalized length will be 2 octets."

**Comment by andris9** [comment]
This might be invalid indeed. I have moved on from this repo to [this code](https://github.com/nodemailer/nodemailer/tree/master/lib/dkim) and do not use it myself anymore so I haven't really cared about if it works or not.

**Comment by andris9** [comment]
Here are the relevant [test cases](https://github.com/nodemailer/nodemailer/blob/master/test/dkim/dkim-test.js) to see how the new DKIM signing can be used. You can basically use it by calling `const DKIM = require('nodemailer/lib/dkim')` and then using as in the test cases. This version should handle empty message body correctly.
